model_configs:
  deepseek:
    api_base: "https://api.deepseek.com/v1"
    api_key: "your-api-key"
    model: "deepseek-chat"
  
  doubao:
    api_base: "https://ark.cn-beijing.volces.com/api/v3"
    api_key: "your-api-key"
    model: "doubao-1-5-pro-32k-250115"
  
  wenxin:
    api_base: "https://qianfan.baidubce.com/v2"
    api_key: "your-api-key"
    model: "ernie-3.5-8k"

system:
  max_turns: 50
  temperature: 0.7
  context_window: 30
